  
 let en = {
    "Has successfully completed the Full Stack Development program":"Has successfully completed the Full Stack Development program",
    "Full Stack Software Development":"Full Stack Software Development",
    "Certificate":"Certificate",
    "Has Successfully Completed":"Has Successfully Completed",
    "Has successfully completed":"Has successfully sompleted",
    "Program":"Program",
    "Coding School": "Coding School",
    "Full Stack": "Full Stack",
    "Recognizes that":"Recognizes that",
    "Full Stack Web Development":"Full Stack Web Development",
    "This certificate is valid.":"This certificate is valid.",
    "and it does not expires":"and it does not expires",
    "Hours":"Hours",
    "Issued On":"Issued On",
    "Expired On":"Expired On",
    "Does not expire":"Does not expire",
    "view all certificates":"view all certificates",
    "Download PDF":"Download PDF",
    "Share on LinkedIn":"Share on LinkedIn",
    "Issuer":"Issuer",
    "website":"website",
    "Development":"Development",
    "The Full Stack Development Program":"The Full Stack Development Program",
    "Total Hours":"Total Hours",
    "Certificate of":"Certificate of",
    "to":"to",
    "Development":"Development",
    "And":"and",
    'This document certifies that the student is a Full Stack Web Developer,with proficient knowlege to help in the creation of web applications using HTML/CSS,Javascript, React and REST API using SQL, Python and the Flask Framework':'This document certifies that the student is a Full Stack Web developer,with proficient knowlege to help in the creation of web applications using HTML/CSS,Javascript, React and REST API using SQL, Python and the Flask Framework'
}
let es = {
    "Has successfully completed the Full Stack Development program":"Ha completado con éxito el programa de Desarrollo Full Stack",
    "Full Stack Software Development":"Full Stack Software Development",
    "Certificate":"Certificado",
    "Has Successfully Completed":"Ha completado con éxito",
    "Has successfully sompleted":"Ha completado con éxito",
    "Full Stack": "Full Stack",
    "Program":"Programa",
    "And":"y",
    "Development":"Desarrollo",
    "Coding School": "Coding School",
    "The Full Stack Development Program":"El programa Full Stack Software Development",
    "Recognizes that":"Reconoce que",
    "This certificate is valid.":"Este certificado es valido.",
    "Development":"Desarrollo",
    "Issued On":"Emitido el",
    "Expired On":"Expira el",
    "Does not expire":"No expira",
    "Hours":"Horas",
    "Download PDF":"Descargar PDF",
    "Issuer":"Emisor",
    "website":"pagina web",
    "Certificate of":"Certificado de",
    "to":"para",
    "Total Hours":"Horas Totales",
    "Share on LinkedIn":"Compartir en LinkedIn",
    "and it does not expires":"y no tiene fecha de expiración",
    "view all certificates":"ver todos los certificados",
    "Full Stack Web Development":"Full Stack Web Development",
    'This document certifies that the student is a Full Stack Web Developer,with proficient knowlege to help in the creation of web applications using HTML/CSS,Javascript, React and REST API using SQL, Python and the Flask Framework':'Este documento certifica que el estudiante es un Desarrollador Web Full Stack, con un conocimiento competente para ayudar en la creación de aplicaciones web usando HTML/CSS, Javascript, React y REST API usando SQL, Python y el Framework de Flask'
}
export default { en, es };
